name: "pb"
services:
  pocketbase:
    read_only: true
    image: "pocketbase"
    environment:
      TZ: "Europe/Zurich"
    volumes:
      - "pocketbase.var:/pocketbase/var"
    ports:
      - "8090:8090/tcp"
    networks:
      frontend:
    restart: "always"

volumes:
  pocketbase.var:

networks:
  frontend:
    external: true
