name: "pb"
services:
  pocketbase:
    read_only: true
    image: "ghcr.io/keksiqc/pocketbase:0.29.0"
    environment:
      TZ: "Europe/Berlin"
      PB_ENCRYPTION_KEY: "6bcf9990dd6d401c113b621bf2edeebd" # Change this in production (openssl rand -hex 16)
    volumes:
      - "pocketbase.var:/pocketbase/var"
    ports:
      - "8090:8090/tcp"
    networks:
      frontend:
    restart: "always"

volumes:
  pocketbase.var:

networks:
  frontend:
    external: true
